checklists/newHire.json

Previous anchor (`#heading-2`) does not exist on the https://handbook.18f.gov/hatch-act-foia-ethics-code-of-conduct/ page

Fix link to SF-450 section

---

README.md

It took me a while to figure out why this wouldn't run before I realized I needed to run MongoDB locally. It's mentioned in the requirements, but it's easy to miss and doesn't explicitly say you need to have it running.

Add line about running MongoDB

---

checklists/devTeam.json

It seems like Float is not used for skills tracking, so I removed that language from the task, but I'm not sure if this is correct.

Correct the Float channel, rm references to skills

---

.travis.yml
package.json

Ref #59 
Node 5.10.0 is supported by both Travis and the current cloud.gov Node buildpack. This can supercede #63 while we wait for v6.10.0 support.
@anthonygarvan thoughts?

Use node 5.10.0

---

package.json

This should speed up deployments very slightly since fewer packages will need to be installed. Might not even be noticeable though.

move testing packages to devDependencies, closes #60

---

package.json

- gets rid of `npm` warning about not having a repository specified
- ref #60 again. I neglected to move phantom to devDependencies previously. This might actually have a noticeable impact on deploying since it will no longer have to download the phantomjs binary

add repo to package.json; move phantom to devDeps

---

.eslintrc
api/api.js
api/github.js
app.js
karma.conf.js
package.json
spec/apiSpec.js
spec/frontEndSpec.js
spec/runBackendTests.js

Add eslint with airbnb/legacy config

---

checklists/newHire.json

The 2FA link should go to https://handbook.18f.gov/equipment/#phone, not `#iphone` (which doesn't seem to exist).

#iphone -> #phone in 2FA auth link

---

api/api.js

`JSON.parse(JSON.stringify(obj))` produces a copy of the input `obj`.
When that line was removed from this function, the original input `checklist` obj got mutated by the `splice`, which removed all the `dependsOn` members from each item.
Comment has been added to explain the purpose of the parse-stringify line.

revert removal of parse-stringify

---

checklists/newHire.json

Looks like the heading name was changed to just "Listservs", breaking the named anchor link.

Fix broken named anchor link to #listservs

---

app.js
package.json
spec/runBackendTests.js

This simplifies app.js by removing the `getApp` function. Instead of passing in mock objects during testing, we instead use mockery to hook into node's require system, replacing instances of some modules with local mocks.
@anthonygarvan - thoughts?

use mockery during backend testing

---

README.md
app.js

This change will cause the app to throw an error on start if a required environment variable is missing, which should prevent problems like the one we had today where the production app did not have `GITHUB_ORG` specified.

add check for required environment variables

---

package.json
private/js/app.js
private/tmpl/checklists.tmpl.html
private/tmpl/preview.tmpl.html
spec/frontend/frontEndSpec.js

Ready for review. Ref #44 
Adds a "Preview" button to the checklist cards so that interested users can see the task names of the selected checklist. The tasks are displayed by `displayName`, and simply sorted by `daysToComplete` instead of going through the dependency tree to figure out exact ordering. The preview dialog includes an "Assign to Me" button to launch the Assign to Me dialog when clicked.
Also made a minor adjustment to the checklist card layout so that the card size flexes to full width on `xs` (< 600px) screen sizes.
cc @anthonygarvan

Preview checklist

---

.eslintignore
.eslintrc
README.md
api/api.js
package.json
scripts/addEstimatedDueDate.js

- Use `airbnb-base/legacy` config for eslint, which removes the need for the react-specific eslint packages that aren't applicable to this project.
- Add an npm command to run eslint: `npm run eslint`.
- Bring a couple files up to linting standards.
Closes #89

Use airbnb-base eslint config

---

checklists/newHire.json

We're deprecating the long-form bio on 18f.gsa.gov. Leaving it in the checklist is misleading.

Remove the "write bio" item

---

Dockerfile
README.md
api/api.js
docker-compose.yml

This PR adds necessary files for running Checklistomania via docker/docker-compose. It makes setting up a local dev version of the app much simpler since just two commands are needed to get up and running: `docker-compose build` and `docker-compose up`. Devs will no longer need to install mongo locally or setup env vars.
closes #99
Please review when you get a chance, @anthonygarvan 
Much of this is based on work by @toolness in other projects.

add Docker for easy dev

---

checklists/buddy.json

Once upon a time, we had a weekly project intake meeting. We no longer do.
(This raises a larger question about how we orient newcomers to the staffing and resourcing process. That's arguably out of scope for this PR, but suggestions are welcome.)

Remove reference to intake meeting

---

checklists/newHire.json

With Phaedra's departure, the URL slug for the welcome page has changed.

Fix welcome URL

---

spec/backend/checklistSpec.js

This PR adds a test to do some validation of all of the checklist JSON files, ref https://github.com/18F/checklistomania/issues/123. It should help catch issues such as the one documented in https://github.com/18F/checklistomania/issues/121#issuecomment-259762490 (a missing `"dayZero"` item).
A more complete solution would probably be to use http://json-schema.org/, but I don't have time to implement that right now. Maybe we could just create another "help wanted" issue for that?
Thoughts, @anthonygarvan?

Test structure of checklist JSONs

---

checklists/newHire.json

Fix splitting of equipment tasks in new hire checklist.

fix repeated task id

---

spec/backend/checklistSpec.js

Add another checklist file test to make sure all the item names in `dependsOn` actually exist in the checklist.
This PR also includes a light refactoring of the checklist spec to create a new `describe` block per checklist file. This has the benefit of producing better output when one of the tests fails, since it will output exactly which file has the problem.
Closes #134

Test that item dependencies actually exist

---

.cfignore
.gitignore
MIGRATE.md
api/api.js
api/github.js
app.js
docker-compose.yml
lib/env.js
lib/middleware.js
manifests/manifest-dev.yml
manifests/manifest_base.yml
manifests/manifest_dev.yml
manifests/manifest_prod.yml
manifests/manifest_staging.yml
package.json
spec/backend/apiSpec.js
spec/backend/envSpec.js
spec/backend/middlewareSpec.js

This PR makes necessary code changes for migrating Checklistomania from the E/W-cloud.gov platform to the GovCloud-cloud.gov platform.

GovCloud migration
