checklists/newHire.json
=> New hire checklist

checklists/engineeringFacilitator.json
Removed trailing whitespace as well—easier to see the substantive changes here:
https://github.com/18F/checklistomania/pull/18/files?w=1
=> updates to the Engineering Facilitator checklist

checklists/newHire.json
=> Adds travel card task

checklists/newHire.json
=> Fix link to Employee Express

checklists/devTeam.json
- capitalized all tasks titles, removed periods from titles
- periods at end of each description
- minor spacing, etc.
=> general clean-up of devTeam tasks

.travis.yml, README.md, app.js, spec/runBackendTests.js
With this change, the GitHub organization is no longer hardcoded so that
users from outside of 18F can more easily use this project. Inspiration from #42 by @adambray.
=> add use of GITHUB_ORG env variable

README.md
Ref #45 
-specify why GitHub credentials are needed
-better indication that the instructions are for developers
=> more README cleanup/clarification

package.json
This moves the app to a supported CF buildpack
=> specify ^4.4.2 as node engine

README.md
Also: Use preferred spelling of Node.js; added a missing period.
=> Add note about using same version of Node.js as in package.json

private/tmpl/add-user.tmpl.html, private/tmpl/assign-dialog.tmpl.html, private/tmpl/checklists.tmpl.html, private/tmpl/tasks.tmpl.html, private/tmpl/users.tmpl.html
Only cleanup, no functionality changes
=> improve indentation consistency

package.json
otherwise who knows what yer gonna get
=> specify express version

private/js/app.js
Somehow missed this file in the previous linting PR
=> lint client side app.js

api/api.js, app.js
- remove bodyParser.urlencoded middleware since it is unused
- add console.log message when server starts
=> fix session and bodyParser deprecation warnings

checklists/devTeam.json
I updated the link as discussed in this issue:
https://github.com/18F/checklistomania/issues/95
=> updating the link for github resources for dev todo

checklists/engineeringDirector.json
moved some items from engineeringDirector.json list to engineeringFacilitator.json list.
=> Moved some items from Director to Facilitator list

checklists/newHire.json
* Removed Team API references for now, as these PRs are not getting merged regularly and the API is in an unclear state
* Removed reference to the fictional "SF-450" form
* Added a reference to the OGE-450 form, with instructions and a link to the form
* Removed vague instructions about getting software licenses
=> Updating onboarding checklist

checklists/newHire.json
=> Changing link to invite for OGE-450 form

checklists/newHire.json
Updated URL to jump to the correct anchor tag
=> Updated Anchor Tag

checklists/new-supervisor.json
json copied in from other files
=> Create supervisor training list

checklists/AcquisitionTeam.json, checklists/allDirectorsSelection.json, checklists/buddy.json, checklists/designTeam.json, checklists/devTeam.json, checklists/engineeringDirector.json, checklists/engineeringFacilitator.json, checklists/newHire.json, checklists/productTeam.json, checklists/productTeamDirector.json, checklists/strategyTeam.json, checklists/supervisorTeam.json, checklists/talentTeam.json
Fixing issue 
Consider changing descriptions of lists to not use the word "TODO" #71
=> remove TODO

checklists/newSupervisorTraining.json
=> remove TODO in checklistDescription

.travis.yml, Dockerfile, package.json
=> upgrade to node 6.9.1; rm phantom install from dockerfile; upgrade karma pkgs

.travis.yml, Dockerfile, README.md, bower.json, checklists/AcquisitionTeam.json, checklists/allDirectorsSelection.json, checklists/buddy.json, checklists/designTeam.json, checklists/devTeam.json, checklists/engineeringDirector.json, checklists/engineeringFacilitator.json, checklists/newHire.json, checklists/newSupervisorTraining.json, checklists/productTeam.json, checklists/productTeamDirector.json, checklists/strategyTeam.json, checklists/supervisorTeam.json, checklists/talentTeam.json, docker-compose.yml, package.json, spec/backend/checklistSpec.js
Made a few formatting correction and turn "receive computer, phone, badge" into three separate items.  Changed Leah to Qituwra
=> Made corrections and split computer, phone, badge

.travis.yml, Dockerfile, README.md, bower.json, checklists/AcquisitionTeam.json, checklists/allDirectorsSelection.json, checklists/buddy.json, checklists/designTeam.json, checklists/devTeam.json, checklists/engineeringDirector.json, checklists/engineeringFacilitator.json, checklists/newHire.json, checklists/newSupervisorTraining.json, checklists/productTeam.json, checklists/productTeamDirector.json, checklists/strategyTeam.json, checklists/supervisorTeam.json, checklists/talentTeam.json, docker-compose.yml, package.json, spec/backend/checklistSpec.js
1.  deleted reference to offsite
2.  replaced OCSIT link with TTS
3.  clarified weekly all-hands meeting
4.  updated 18F calendars URL
=> Multiple updates to new hire checklist

checklists/buddy.json, checklists/newHire.json
1) clearer instructions about new hire’s email
2) changed Chicago onboarding end time
3) added URL for mailing lists
4) clearer instructions for All-Hands
5) changed wording for office tour
6) deleted duplicate task referencing calendars and listservs
=> Buddy list multiple updates

checklists/newHire.json
Added instructions to “Set up Slack” and “Set up Github” so they aren’t
reliant on Delores messages.  Also added info to “Secure your laptop”
to make sure new hires download Managed Software Center and ClamXav
=> Updates to New Hire Checklist

checklists/AssigneeDetail.json
Created new checklist .json file
=> New Checklist for Assignees/Details

views/index.html
=> change 'Tasks' to 'My Tasks'

checklists/productTeam.json, checklists/productTeamDirector.json
Updated tasks to reflect current onboarding process
=> Updated tasks to reflect new onboarding

checklists/productTeam.json
=> New checklist items

checklists/intern.json
Removed some steps and added some.
=> New Intern Checklist Updates

checklists/newHire.json
Added onboarding survey at the end of the new hire checklist
=> Added onboarding survey

checklists/newHire.json
=> 18f to TTS new hire

checklists/intern.json, checklists/newHire.json
Updated some verbiage and links in the New Hire and Intern checklists
=> New hire checklist survey

checklists/newHire.json
replaced old contact directory with new emergency contact form
=> Emergency contact
